#!/usr/bin/env bash
#file transfered from client to server
#
# vars
path="$(cd "$(dirname "$(BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
filename=$(basename "$BASH_SOURCE")
Brown='\e[0;33m'
reset='\033[0m'
file="$1"
ip="$2"
user="ubuntu"
key="~/.ssh/id_rsa"


if [ $# -eq 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
