#!/usr/bin/env bash
#   Create file /var/run/myscript.pid containing script PID
#   Displays "To infinity and beyond" indefinitely
#   Deletes file /var/run/myscript.pid and terminates upon
#+  receiving SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
