#!/usr/bin/env bash
# Displays numbers from 1 to 100 in list format.

for nm in {1..100}
do
  if (( nm % 3 == 0 && nm % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( nm % 3 == 0 ))
  then
    echo "Fizz"
  elif (( nm % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$num"
  fi
done
