#!/usr/bin/env bash
# "Best School" displays 10 times using a while loop.
#   On 9th iteration, displays "Hi" before "Best School"

cnt=0

while [ $cnt -lt 10 ]
do
  if [ $cnt -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( cnt++ ))
done
